### ISSUE TITLE
Deprecation with Auto-Injection

### ISSUE THREAD

**Issue by alunasky** [webeweb/jquery-datatables-bundle#1]
> User Deprecated: Auto-injection of the container for "WBW\Bundle\JQuery\DataTablesBundle\Controller\DataTablesController" is deprecated since Symfony 4.2. Configure it as a service instead.

This is giving a deprecated call, can this be ignored?

**Comment by webeweb** [comment]
Hi,

This warning can be ignored. We use this bundle into Symfony 4.2 and it works perfectly.

Best regards
